lib changed
codecrafters-io/legacy-course-sdk pull request #6
Opened 2022-11-12 12:36 UTC by nikandfor

Please guide me if the code could be done more idiomatic for ruby

2022-11-12 13:22 UTC, rohitpaulk requested changes
Hey @nikandfor - looking good! We can forego the backward compatibility code here to keep things simple. We can open PRs in the course repositories that use this branch, and merge everything together once we know tests pass everywhere.

2022-11-12 13:22 UTC, rohitpaulk commented on lib/models.rb
> +  def dir_name
```suggestion
  def solution_dir
```

(similar to `Course#solutions_dir` and `Course#dir`)

2022-11-12 13:22 UTC, rohitpaulk commented on lib/models.rb
> +    stage_dir = [
We don't need the backward compatibility to work - we can just rely on `stage.solution_dir` directly

2022-11-12 13:22 UTC, rohitpaulk commented on lib/solution_tester.rb
> +    @course.stage_path(@language, stage, "code")
```suggestion
    "#{stage.solution_dir}/code"
```

(i.e. no backward compatibility)

2022-11-12 13:22 UTC, rohitpaulk commented on lib/solution_tester.rb
> +    File.directory?(@course.stage_path(@language, stage))
```suggestion
    File.directory?(stage.solution_dir)
```

(i.e. no backward compatibility)

2022-11-12 13:52 UTC, nikandfor commented
made it simple

2022-11-12 13:53 UTC, rohitpaulk approved these changes
Looks good!

2022-11-12 14:01 UTC, nikandfor commented
If I change `.github/workflows/test.yml` in courses repos to use this branch we'll need to return them back after rename PRs are merged. Is it ok?

2022-11-12 14:10 UTC, rohitpaulk commented
@nikandfor yep, that works! The only requirement here is that any downtime (i.e. tests not working because repositories are incompatible) should be limited to under an hour or so. Another option would be to merge this in when ready, and then rename the other PRs back to master just before merging, instead of after.

2022-11-12 15:24 UTC, nikandfor commented
[git](https://github.com/codecrafters-io/build-your-own-git/pull/17)
sdk: nikandfor/rename_stage_dirs
naming: new
tests: all pass

[grep](https://github.com/codecrafters-io/build-your-own-grep/pull/15)
sdk: main
naming: new
tests: verify_templates_compiled failed, others pass

[redis](https://github.com/codecrafters-io/build-your-own-redis/pull/52)
sdk: nikandfor/rename_stage_dirs
naming: old
tests: all pass

looks like with the new sdk tests pass with or without renaming. If it's not a bug, we can safely merge this PR and merge the others easily not changing workflows.

2022-11-12 19:23 UTC, rohitpaulk commented
> looks like with the new sdk tests pass with or without renaming. If it's not a bug, we can safely merge this PR and merge the others easily not changing workflows.

@nikandfor ah, didn't think of this. Let's have the tests fail - any directories that don't match the recommended format should throw a friendly error (I'm assuming the tests pass _because_ it's ignoring the older directories)

2022-11-12 19:25 UTC, nikandfor commented
Should it be a separate test or use one of existing?

2022-11-12 19:26 UTC, rohitpaulk commented
@nikandfor I think it'd fit neatly within `SolutionTester`, somewhere here: https://github.com/codecrafters-io/course-sdk/blob/73ffd37e527c0a6c59fbd6e8f6159a4d3bb1d6ed/lib/solution_tester.rb#L19. Feel free to create a new test if that's easier though - I'm fine with either 🙂

2022-11-12 19:27 UTC, rohitpaulk commented
Whether an existing file or new one, let's have it imported/run within https://github.com/codecrafters-io/course-sdk/blob/main/scripts/test.rb

2022-11-13 14:11 UTC, nikandfor commented
Wouldn't it be better to run it as a separate test here?
<img width="848" alt="image" src="https://user-images.githubusercontent.com/6097822/201526160-4d4be7de-8c7d-48d0-8455-2b9319ebcade.png">

2022-11-13 14:16 UTC, rohitpaulk commented
@nikandfor hmm, yeah good idea. So there'd still be a single https://github.com/codecrafters-io/course-sdk/blob/main/.github/workflows/test-course-definition.yml workflow file to use, yes?

2022-11-13 14:24 UTC, nikandfor commented
Yes, we don't need a separate file, but it would be useful to see two separate results: if tests pass and if we have unexpected folders.

2022-11-13 14:27 UTC, rohitpaulk commented
@nikandfor yep, makes sense!

2022-11-13 15:38 UTC, nikandfor commented
https://github.com/codecrafters-io/build-your-own-redis/actions/runs/3455873160/jobs/5768217454

2022-11-13 23:59 UTC, rohitpaulk commented on scripts/validate_stages_naming.sh
> +			echo >&2 "unexpected file: $lang/$dir"
We can remove the `stages_old` handling in this file to keep things simple (people don't have to know what the "old" format was). 

Let's make a small change to the error message to say what is expected. Something like `unexpected file: go/blah, expected format: <stage_number>-<stage_slug> (ex: "01-init")`.

2022-11-14 15:46 UTC, nikandfor commented
All five courses are green now, can we go further?

2022-11-14 15:50 UTC, rohitpaulk commented
@nikandfor yep, feel free to start merging 👍

2022-11-14 15:52 UTC, merged

2022-11-14 16:27 UTC, nikandfor commented
done, all tests pass